### PR TITLE
Some fixes and dependency remove

### PR DESCRIPTION
**Pull request by kibaekkim**
This is a fork from `stable/0.96`. I fixed a couple memory issues and removed the denpendency to `Clp`, which may not be necessary to this package.

### CODE REVIEW

**Comment by tkralphs** [comment]
Hi @kibaekkim The CLA error should go away if you add the e-mail address you used to make the commits to your Github account. Alternatively, you could change the author of those two commits, which might be better. Could you also rebase on the current master? Right now, you are asking to move some commits from stable/0.96 into master that don't really belong there.

**Comment by tkralphs** [comment]
Looks like some tests are failing as well...

**Comment by kibaekkim** [comment]
I have edited the author info for some commits to address the CLA issue. Once addressing the travis issue, I will close and reopen this PR.

**Comment by tkralphs** [comment]
Hey @kibaekkim, sorry for making this more difficult for you, since we appreciate your contribution, but there seems to be a lot of stuff getting mixed in to one single PR and I don't easily see how it's all related. It would be helpful if you could clearly separate out related sets of changes and explain the rationale for the changes. At a glance, I see at least a few things that we can't really merge. 

- The naming of the `README` to `README.md` will happen eventually, but it requires some changes to the configure script to avoid a failure when installing and I would prefer to do that in combination with some other changes that are coming soon anyway.
- `COIN_HAS_CLP` is defined by the build system and is used the same way across all projects in the Optimization Suite, so the changes you made in cb214bac are also not something I would want to merge. If you explain your intent, I'm sure we can figure out a proper workaround. 
- Removing Clp as a dependency is also probably not quite the right fix for what you want. It's easy to skip projects that you don't want with `coinbrew` using `--skip`. If the dependency is removed altogether, then others won't be able to use coinbrew to get Clp if they want it.

There may be other small things that I haven't noticed yet. When you reopen the PR, maybe you can try to distill the commits down to an essential set with some explanation.

**Comment by kibaekkim** [comment]
Some `travis-ci` tests failed. It looks like something related to `FlopCpp 1.2` on Macosx with clang.

**This must be known by looking at the `travis-ci` history.**

**Pull request closed without merging**
