### PR TITLE
Fixing mismatch of realloc and delete [] applied to rowNode and colum…

### PR DESCRIPTION
**Pull request by bcdandurand**
…nNode.

I am planning to use and perhaps modify Smi in project, and in preparing to do so, after compiling and trying the example, I applied valgrind to find and fix the minor memory violation issue that was uncovered. I recompiled with `make test` and reran the example `stoch` application successfully.

### CODE REVIEW

**Comment by kingaj12** [comment]
... great!  thanks for the valgrind fix

**Comment by svigerske** [comment]
Shouldn't that go to the Smi svn repo, otherwise it gets overwritten with the next mirroring from svn to github? (CC @tkralphs)

**Comment by tkralphs** [comment]
Yes, as of now, Smi is still mirrored from SVN. We can switch off mirroring at any time and start using git, given the low volume of commits and releases, but note that we still don't have fully automated scripts for making releases from git-managed projects or a recommended git workflow for the projects within the Optimization Suite. It could possibly be easier to stick with SVN for the short term. 

But in any case, for this patch, yes, it would need to be committed through SVN this time. It's likely already been over-written.

**Comment by kingaj12** [comment]
Hi Ted - can we turn off the svn mirror?  I prefer to use github now (yes, even after lots of headbanging-on-keyboard)
 
I'll try to rerun the patch
 
Alan KingAI & Blockchain, Finance
IBM Research
 
 
----- Original message -----From: Ted Ralphs <notifications@github.com>To: coin-or/Smi <Smi@noreply.github.com>Cc: Alan King <kingaj@us.ibm.com>, State change <state_change@noreply.github.com>Subject: [EXTERNAL] Re: [coin-or/Smi] Fixing mismatch of realloc and delete [] applied to rowNode and colum… (#2)Date: Wed, Apr 29, 2020 12:30 PM 
 
Yes, as of now, Smi is still mirrored from SVN. We can switch off mirroring at any time and start using git, given the low volume of commits and releases, but note that we still don't have fully automated scripts for making releases from git-managed projects or a recommended git workflow for the projects within the Optimization Suite. It could possibly be easier to stick with SVN for the short term.
But in any case, for this patch, yes, it would need to be committed through SVN this time. It's likely already been over-written.

**Comment by tkralphs** [comment]
OK, I've turned off mirroring now, we're officially on git. If you want to re-apply this PR, here is the patch.

https://github.com/coin-or/Smi/pull/2.patch

I can also do it.

**Comment by kingaj12** [comment]
Thanks, Ted.  I'm a little uncertain about patching this file .. grateful if you can do it.
 
Alan KingAI & Blockchain, Finance
IBM Research
 
 
----- Original message -----From: Ted Ralphs <notifications@github.com>To: coin-or/Smi <Smi@noreply.github.com>Cc: Alan King <kingaj@us.ibm.com>, State change <state_change@noreply.github.com>Subject: [EXTERNAL] Re: [coin-or/Smi] Fixing mismatch of realloc and delete [] applied to rowNode and colum… (#2)Date: Thu, Apr 30, 2020 4:46 PM 
 
OK, I've turned off mirroring now, we're officially on git. If you want to re-apply this PR, here is the patch.
https://github.com/coin-or/Smi/pull/2.patch
I can also do it.

**Comment by tkralphs** [comment]
OK, done in ac7a51c.

**Pull request merged**
